# Generated by Django 5.1.2 on 2024-12-19 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_role', models.CharField(max_length=255)),
                ('min_member', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_member', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('competitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogue.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('prev_performance', models.CharField(blank=True, max_length=255, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogue.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('your_city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Others')], max_length=1)),
                ('Postal_code', models.IntegerField(blank=True, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogue.competition')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogue.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vogue.team')),
            ],
        ),
    ]
